# Creating tables in our warehouse

In [1]:
import psycopg2
import pandas as pd

In [2]:
db_params = {
    'host': '194.171.191.226',
    'port': '6379',
    'database': 'postgres',
    'user': 'group15',
    'password': 'blockd_2024group15_73'
}

In [3]:
conn_psycopg2 = psycopg2.connect(**db_params)
cursor = conn_psycopg2.cursor()

##  Accident data 17-23

In [4]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.accident_data_17_23 AS
        SELECT * FROM data_lake.accident_data_17_23;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [5]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.accident_data_17_23;
'''

cursor.execute(query)

# Fetch all rows
new_accident_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
new_accidents = pd.DataFrame(new_accident_rows, columns=column_names)

display(new_accidents)

,Year,Accident severity,municipality,town,First Mode of Transport,Second mode of Transport,Area Type,Light condition,Road Location,Road condition,Road surface,Road situation,Speed limit,street,weather,accidents
0,2017,Fatal,Breda,BREDA,Car,Pedestrian,Urban area,Darkness,Intersection,Wet/damp,Brick,Bend,30 km/h,Valkeniersplein,Rain,1
1,2017,Fatal,Breda,BREDA,Lorry,Other,Urban area,Daylight,Intersection,Wet/damp,Brick,Intersection - 4 arms,50 km/h,Markendaalseweg,Dry,1
2,2017,Fatal,Breda,BREDA,Lorry,Other,Urban area,Daylight,Road section,Dry,Asphalt (other),Straight road,50 km/h,Academiesingel,Dry,1
3,2017,Injured,Breda,BAVEL,Car,Lorry,Rural area,Darkness,Road section,Wet/damp,Asphalt (other),Bend,120 km/h,KP ST.ANNABOSCH,Dry,1
4,2017,Injured,Breda,BAVEL,Car,Other,Rural area,Darkness,Road section,Wet/damp,Porous asphalt,Straight road,130 km/h,RYKSWG,Rain,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6897,2023,Fatal,Breda,BREDA,Car,Moped,Urban area,Daylight,Road section,Dry,Asphalt (other),Straight road,50 km/h,Terheijdenseweg,Dry,1
6898,2023,Fatal,Breda,BREDA,Car,Car,Urban area,Darkness,Intersection,Dry,Asphalt (other),Intersection - 4 arms,70 km/h,Rijsbergseweg,Dry,1
6899,2023,Fatal,Breda,BREDA,Other,Other,Rural area,Daylight,Road section,Wet/damp,Porous asphalt,Straight road,100 km/h,RYKSWG,Dry,1
6900,2023,Fatal,Breda,PRINSENBEEK,Car,Car,Rural area,Darkness,Road section,Dry,Porous asphalt,Straight road,130 km/h,RYKSWG,Dry,1
6901,2023,Fatal,Breda,ULVENHOUT,Other vehicle,Bicycle,Rural area,Daylight,Intersection,Dry,Asphalt (other),Intersection - 4 arms,60 km/h,Rouppe van der Voortlaan,Dry,1

## Safe driving

In [6]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.safe_driving AS
        SELECT * FROM data_lake.safe_driving;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [7]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.safe_driving;
'''

cursor.execute(query)

# Fetch all rows
safe_driving_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
safe_driving = pd.DataFrame(safe_driving_rows, columns=column_names)

display(safe_driving)

,eventid,event_start,event_end,duration_seconds,latitude,longitude,speed_kmh,end_speed_kmh,maxwaarde,category,incident_severity,is_valid,road_segment_id,road_manager_type,road_number,road_name,place_name,municipality_name,road_manager_name
0,114074654,2023-04-20 15:22:52.800,2023-04-20 15:22:54.800,2.0,51.59626,4.750160,30.067245,23.846440,0.803063,HARSH CORNERING,HC1,True,600750253,G,,Lunetstraat,Breda,Breda,Breda
1,114106469,2023-04-20 07:43:37.500,2023-04-20 07:43:38.800,1.3,51.59366,4.821790,33.890450,34.131660,0.730642,HARSH CORNERING,HC1,True,600122980,G,,Tilburgseweg,Breda,Breda,Breda
2,114224520,2023-04-20 15:34:16.400,2023-04-20 15:34:25.000,8.6,51.62473,4.731699,0.792001,2.124004,1.202180,HARSH CORNERING,HC1,False,219208060,G,,Zwanebloem,Breda,Breda,Breda
3,114230868,2023-04-20 10:02:42.700,2023-04-20 10:02:44.100,1.4,51.57934,4.788980,20.498440,27.133250,0.791797,HARSH CORNERING,HC1,True,600753719,G,,Generaal Maczekstraat,Breda,Breda,Breda
4,114263402,2023-04-20 17:22:39.700,2023-04-20 17:22:41.200,1.5,51.59299,4.781110,12.988822,18.021627,1.041246,HARSH CORNERING,HC2,False,600752601,G,,Delpratsingel,Breda,Breda,Breda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964483,114224185,2023-04-20 15:03:18.900,2023-04-20 15:03:23.300,4.4,51.58070,4.777853,5.724010,5.724010,1.161946,ACCELERATING,HA1,False,225198094,G,,Wilhelminasingel,Breda,Breda,Breda
964484,114192172,2023-04-20 16:38:37.300,2023-04-20 16:38:37.900,0.6,51.59337,4.778210,9.597616,8.654415,0.846515,BRAKING,HB1,False,225201050,G,,Academiesingel,Breda,Breda,Breda
964485,114228627,2023-04-20 14:52:28.000,2023-04-20 14:52:44.000,16.0,51.58720,4.826590,100.749760,90.298960,101.224970,SPEED,SP3,False,600756776,G,,Minervum,Breda,Breda,Breda
964486,114212870,2023-04-20 14:34:38.000,2023-04-20 14:34:39.300,1.3,51.59689,4.791730,25.120846,31.543255,0.851343,HARSH CORNERING,HC1,True,600753786,G,,Doornboslaan,Breda,Breda,Breda
964487,114243902,2023-04-20 18:34:10.900,2023-04-20 18:34:12.900,2.0,51.58137,4.736449,28.620043,27.072046,0.819156,HARSH CORNERING,HC1,False,600919160,G,,Ettensebaan,Breda,Breda,Breda

## Temperature

In [8]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.temperature AS
        SELECT * FROM data_lake.temperature;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [9]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.temperature;
'''

cursor.execute(query)

# Fetch all rows
temperature_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
temperature = pd.DataFrame(temperature_rows, columns=column_names)

display(temperature)

,dtg,LOCATION,NAME,latitude,longitude,altitude,u_bool_10,t_dryb_10,tn_10cm_past_6h_10,t_dewp_10,t_dewp_sea_10,t_dryb_sea_10,tn_dryb_10,t_wetb_10,tx_dryb_10,u_10,u_sea_10
0,2017-01-03 03:20:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.6,0.9,1.2,1.6,1.421300,1.6,97.0,None,None,None
1,2017-01-03 03:30:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.5,0.6,1.2,1.5,1.322090,1.6,97.0,None,None,None
2,2017-01-03 03:40:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.6,0.5,1.2,1.5,1.421300,1.7,97.0,None,None,None
3,2017-01-03 03:50:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.8,0.5,1.3,1.6,1.559385,1.9,96.0,None,None,None
4,2017-01-03 04:00:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.7,0.6,1.2,1.7,1.460458,1.8,96.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954283,2017-01-03 02:30:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.3,0.4,0.9,1.3,1.123727,1.4,97.0,None,None,None
954284,2017-01-03 02:40:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.3,0.4,0.9,1.3,1.064771,1.4,96.0,None,None,None
954285,2017-01-03 02:50:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.3,0.3,0.9,1.2,1.123697,1.3,97.0,None,None,None
954286,2017-01-03 03:00:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.4,0.4,1.0,1.2,1.222899,1.4,97.0,None,None,None
954287,2017-01-03 03:10:00,350_T_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,1.0,1.6,0.8,1.3,1.4,1.421299,1.6,97.0,None,None,None

## Wind

In [10]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.wind AS
        SELECT * FROM data_lake.wind;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [11]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.wind;
'''

cursor.execute(query)

# Fetch all rows
wind_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
wind = pd.DataFrame(wind_rows, columns=column_names)

display(wind)

,dtg,LOCATION,NAME,latitude,longitude,altitude,ff_10m_10,dd_10,ddn_10,dd_std_10,ddx_10,ff_sensor_10,ff_10m_std_10,fx_10m_10,fx_10m_md_10,fx_sensor_10,fx_sensor_md_10,squall_10
0,2013-04-22 17:50:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,4.00,247.6,12.8,4.00,0.92,6.66,6.66,6.66,6.7,0.0,None,None
1,2013-04-22 18:00:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,4.41,254.5,16.4,4.41,0.94,6.99,6.99,6.99,7.0,0.0,None,None
2,2013-04-22 18:10:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,3.27,264.5,13.3,3.27,0.78,5.73,6.99,5.73,7.0,0.0,None,None
3,2013-04-22 18:20:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,3.27,264.7,10.7,3.27,0.70,5.44,5.52,5.44,5.5,0.0,None,None
4,2013-04-22 18:30:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,3.27,257.9,11.9,3.27,0.63,5.28,5.44,5.28,5.4,0.0,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098832,2013-04-22 17:00:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,3.67,234.3,17.5,3.67,0.96,6.70,6.70,6.70,6.7,0.0,None,None
1098833,2013-04-22 17:10:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,4.18,229.3,13.3,4.18,0.92,6.31,6.70,6.31,6.7,0.0,None,None
1098834,2013-04-22 17:20:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,3.50,226.1,13.2,3.50,0.78,6.66,6.66,6.66,6.7,0.0,None,None
1098835,2013-04-22 17:30:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,4.18,228.6,12.0,4.18,0.80,7.05,7.05,7.05,7.1,0.0,None,None
1098836,2013-04-22 17:40:00,350_W_a,Gilze-Rijen locatie A,51.565,4.935278,14.9,3.40,235.2,15.6,3.40,0.74,5.89,7.05,5.89,7.1,0.0,None,None

## Precipitation

In [12]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.precipitation AS
        SELECT * FROM data_lake.precipitation;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [13]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.precipitation;
'''

cursor.execute(query)

# Fetch all rows
precipitation_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
precipitation = pd.DataFrame(precipitation_rows, columns=column_names)

display(precipitation)

,dtg,LOCATION,NAME,latitude,longitude,altitude,dr_pws_10,dr_regenm_10,ww_cor_10,ri_pws_10,ri_regenm_10
0,2011-12-28 10:10:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
1,2011-12-28 10:20:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
2,2011-12-28 10:30:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
3,2011-12-28 10:40:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
4,2011-12-28 10:50:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1098427,2011-12-28 09:20:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
1098428,2011-12-28 09:30:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
1098429,2011-12-28 09:40:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
1098430,2011-12-28 09:50:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0
1098431,2011-12-28 10:00:00,350_R_a,Gilze-Rijen locatie 10t,51.565,4.935278,14.9,0.0,0.0,0.0,0.0,0.0

## Greenery

In [14]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.greenery AS
        SELECT * FROM data_lake.greenery;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [15]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.greenery;
'''

cursor.execute(query)

# Fetch all rows
greenery_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
greenery = pd.DataFrame(greenery_rows, columns=column_names)

display(greenery)

,_id,_key,namespace,lokaalid,objectbegintijd,objecteindtijd,tijdstipregistratie,eindregistratie,lv_publicatiedatum,bronhouder,inonderzoek,relatievehoogteligging,bgt_status,plus_status,bgt_type,plus_type,longitude,latitude
0,67650,NL.IMGeo.G0718.e6d426485c554192aa662a98db213e33,NL.IMGeo,G0718.e6d426485c554192aa662a98db213e33,2018-12-07,,2019-10-11 10:46:38+02,,2019-10-11 13:05:30+02,G0718,0,0,bestaand,geenWaarde,niet-bgt,boom,3.5941036989021873,51.473933934187826
1,67638,NL.IMGeo.G0718.9033f775c728495fb95f0441fa4e1cfa,NL.IMGeo,G0718.9033f775c728495fb95f0441fa4e1cfa,2018-12-07,,2019-10-11 10:46:38+02,,2019-10-11 13:05:30+02,G0718,0,0,bestaand,geenWaarde,niet-bgt,boom,3.5943538030133335,51.47383426864301
2,67609,NL.IMGeo.G0718.fa4855eed1864ad8b4535623a8939910,NL.IMGeo,G0718.fa4855eed1864ad8b4535623a8939910,2018-12-07,,2018-12-10 09:05:29+01,,2018-12-10 09:45:46+01,G0718,0,0,bestaand,geenWaarde,niet-bgt,boom,3.5939665455647587,51.474091759408076
3,67610,NL.IMGeo.G0718.fc68349b2bdd449783de27c837fbc14c,NL.IMGeo,G0718.fc68349b2bdd449783de27c837fbc14c,2018-12-07,,2018-12-10 09:05:29+01,,2018-12-10 09:45:46+01,G0718,0,0,bestaand,geenWaarde,niet-bgt,boom,3.5940100481317785,51.47417223680421
4,67596,NL.IMGeo.G0718.b8d7be0936b441eab357c819ce76c926,NL.IMGeo,G0718.b8d7be0936b441eab357c819ce76c926,2018-12-07,,2018-12-10 09:05:29+01,,2018-12-10 09:45:46+01,G0718,0,0,bestaand,geenWaarde,niet-bgt,boom,3.5942140352503995,51.47404350679642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888114,1174144,NL.IMGeo.G0599.16fd01755eba4cac9e050210a7e24119,NL.IMGeo,G0599.16fd01755eba4cac9e050210a7e24119,2008-01-15,,2008-01-15 10:08:50+01,,2017-07-17 17:14:08+02,G0599,0,0,bestaand,geenWaarde,niet-bgt,boom,4.424495815610096,51.93801315463025
888115,1173983,NL.IMGeo.G0599.16fd01755eba0cac9e050210a7e24119,NL.IMGeo,G0599.16fd01755eba0cac9e050210a7e24119,2008-01-15,,2008-01-15 10:08:50+01,,2017-07-17 17:14:08+02,G0599,0,0,bestaand,geenWaarde,niet-bgt,boom,4.424524861649347,51.938012961003324
888116,1174116,NL.IMGeo.G0599.16fd017887e04cac9e050210a7e24119,NL.IMGeo,G0599.16fd017887e04cac9e050210a7e24119,2008-01-15,,2008-01-15 10:08:50+01,,2017-07-17 17:14:08+02,G0599,0,0,bestaand,geenWaarde,niet-bgt,boom,4.424539346624447,51.93802990659481
888117,1173487,NL.IMGeo.G0599.16fd017884e90cac9e050210a7e24119,NL.IMGeo,G0599.16fd017884e90cac9e050210a7e24119,2008-01-15,,2008-01-15 10:08:50+01,,2017-07-17 17:14:08+02,G0599,0,0,bestaand,geenWaarde,niet-bgt,boom,4.4235080794686565,51.93918946871269
888118,1173437,NL.IMGeo.G0599.16fd01755e61acac9e050210a7e24119,NL.IMGeo,G0599.16fd01755e61acac9e050210a7e24119,2008-01-15,,2008-01-15 10:08:50+01,,2017-07-17 17:14:08+02,G0599,0,0,bestaand,geenWaarde,niet-bgt,boom,4.423618617878874,51.93923371857104

## Breda road

In [16]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.breda_road AS
        SELECT * FROM data_lake.breda_road;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [17]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.breda_road;
'''

cursor.execute(query)

# Fetch all rows
breda_road_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
breda_road = pd.DataFrame(breda_road_rows, columns=column_names)

display(breda_road)

,_id,_key,namespace,lokaalid,objectbegintijd,objecteindtijd,tijdstipregistratie,eindregistratie,lv_publicatiedatum,bronhouder,inonderzoek,relatievehoogteligging,bgt_status,plus_status,bgt_functie,plus_functie,bgt_fysiekvoorkomen,plus_fysiekvoorkomen,wegdeeloptalud,geometry
0,2533831,NL.IMGeo.G0758.e9413581e36a4be7a7f4531e40991d91,NL.IMGeo,G0758.e9413581e36a4be7a7f4531e40991d91,2014-11-18,,2014-11-18 15:22:16+01,,2015-12-03 13:31:11+01,G0758,0,0,bestaand,geenWaarde,fietspad,waardeOnbekend,gesloten verharding,waardeOnbekend,0.0,"[[(51.5720558098156, 4.777635271765369), (51.5..."
1,2533833,NL.IMGeo.G0758.7fe9a4d6585e4bd0be6ef6110cf7ee4f,NL.IMGeo,G0758.7fe9a4d6585e4bd0be6ef6110cf7ee4f,2014-11-18,,2014-11-18 15:22:16+01,,2015-12-03 13:31:11+01,G0758,0,0,bestaand,geenWaarde,fietspad,waardeOnbekend,gesloten verharding,waardeOnbekend,0.0,"[[(51.57211781678044, 4.777537417712849), (51...."
2,2535891,NL.IMGeo.G0758.ce3ba43543dd477bbe585e80de96c26b,NL.IMGeo,G0758.ce3ba43543dd477bbe585e80de96c26b,2014-11-18,,2014-11-18 15:22:16+01,,2015-12-03 13:31:11+01,G0758,0,0,bestaand,geenWaarde,fietspad,waardeOnbekend,gesloten verharding,waardeOnbekend,0.0,"[[(51.57216553995369, 4.777484284794475), (51...."
3,2535884,NL.IMGeo.G0758.8a18a26fbc7d4ca0bb5754ef8dedd685,NL.IMGeo,G0758.8a18a26fbc7d4ca0bb5754ef8dedd685,2014-11-18,,2014-11-18 15:22:16+01,,2015-12-03 13:31:11+01,G0758,0,0,bestaand,geenWaarde,voetpad,waardeOnbekend,open verharding,waardeOnbekend,0.0,"[[(51.57217086343215, 4.777453661428858), (51...."
4,2533830,NL.IMGeo.G0758.b092d73c56ff4afb81b315a5625c08c2,NL.IMGeo,G0758.b092d73c56ff4afb81b315a5625c08c2,2014-11-18,,2014-11-18 15:22:16+01,,2015-12-03 13:31:11+01,G0758,0,0,bestaand,geenWaarde,voetpad,waardeOnbekend,open verharding,waardeOnbekend,0.0,"[[(51.57207704416804, 4.777570291268723), (51...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75893,2663538,NL.IMGeo.G0826.0928f986dcd9a9f9e0534a07c00a7619,NL.IMGeo,G0826.0928f986dcd9a9f9e0534a07c00a7619,2014-10-14,,2014-10-14 13:51:15+02,,2016-05-14 00:26:00+02,G0826,0,0,bestaand,geenWaarde,rijbaan lokale weg,waardeOnbekend,gesloten verharding,asfalt,0.0,"[[(51.631895310995574, 4.859081038532128), (51..."
75894,2663541,NL.IMGeo.G0826.0928f986e90ba9f9e0534a07c00a7619,NL.IMGeo,G0826.0928f986e90ba9f9e0534a07c00a7619,2014-08-13,,2014-08-13 15:16:55+02,,2016-05-14 00:26:00+02,G0826,0,0,bestaand,geenWaarde,voetpad,waardeOnbekend,open verharding,tegels,0.0,"[[(51.631941309887026, 4.858852824845664), (51..."
75895,2663539,NL.IMGeo.G0826.0928f986e1e2a9f9e0534a07c00a7619,NL.IMGeo,G0826.0928f986e1e2a9f9e0534a07c00a7619,2014-08-13,,2014-08-13 15:16:55+02,,2016-05-14 00:26:00+02,G0826,0,0,bestaand,geenWaarde,fietspad,waardeOnbekend,open verharding,tegels,0.0,"[[(51.631935771048894, 4.858880303751935), (51..."
75896,2663579,NL.IMGeo.G0826.0928f986e214a9f9e0534a07c00a7619,NL.IMGeo,G0826.0928f986e214a9f9e0534a07c00a7619,2014-10-14,,2014-10-14 13:51:15+02,,2016-05-14 00:26:00+02,G0826,0,0,bestaand,geenWaarde,fietspad,waardeOnbekend,open verharding,tegels,0.0,"[[(51.631781012772976, 4.859083511321466), (51..."
75897,2663543,NL.IMGeo.G0826.0928f986ea22a9f9e0534a07c00a7619,NL.IMGeo,G0826.0928f986ea22a9f9e0534a07c00a7619,2014-10-15,,2014-10-15 15:50:39+02,,2016-05-14 00:26:00+02,G0826,0,0,bestaand,geenWaarde,voetpad,waardeOnbekend,open verharding,tegels,0.0,"[[(51.63185027617402, 4.859134514141542), (51...."

## Accidents

In [18]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.accidents AS
        SELECT * FROM data_lake.accidents;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [19]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.accidents;
'''

cursor.execute(query)

# Fetch all rows
accidents_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
accidents = pd.DataFrame(accidents_rows, columns=column_names)

display(accidents)

,vkl_nummer,regnummer,pvopgem,datum_vkl,dag_code,mnd_nummer,jaar_vkl,tijdstip,uur,ddl_id,...,pve_naam,kdd_naam,plt_naam,dienstcode,dienstnaam,distrcode,distrnaam,dagtype,ind_alc,weeknr
0,320070889389,07-091381,,,,,2007,,,,...,Noord-Brabant,SAMENWERKINGSVERBAND REGIO EINDHOVEN,Regionale Eenheid Oost-Brabant,,,NaN,,,N,
1,320070889434,07-574474,,,,,2007,,,,...,Noord-Brabant,SAMENWERKINGSVERBAND REGIO EINDHOVEN,Regionale Eenheid Oost-Brabant,,,NaN,,,N,
2,320070889450,07-081452,,,,,2007,,,,...,Zeeland,,Regionale Eenheid Zeeland - West-Brabant,,,NaN,,,N,
3,320070889469,07-078227,,,,,2007,,,,...,Zeeland,,Regionale Eenheid Zeeland - West-Brabant,,,NaN,,,J,
4,320070889493,07-081964,,,,,2007,,,,...,Zeeland,,Regionale Eenheid Zeeland - West-Brabant,,,NaN,,,N,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2336967,320070889135,07-050100,,,,,2007,,,,...,Noord-Holland,REGIO NOORD HOLLAND-OV,Regionale Eenheid Midden-Nederland,,,NaN,,,N,
2336968,320070889346,07-574359,,,,,2007,,,,...,Noord-Brabant,SAMENWERKINGSVERBAND REGIO EINDHOVEN,Regionale Eenheid Oost-Brabant,,,NaN,,,N,
2336969,320070889354,07-574352,,,,,2007,,,,...,Noord-Brabant,SAMENWERKINGSVERBAND REGIO EINDHOVEN,Regionale Eenheid Oost-Brabant,,,NaN,,,N,
2336970,320070889362,07-574323,,,,,2007,,,,...,Noord-Brabant,SAMENWERKINGSVERBAND REGIO EINDHOVEN,Regionale Eenheid Oost-Brabant,,,NaN,,,N,
2336971,320070889370,07-572488,,,,,2007,,,,...,Noord-Brabant,SAMENWERKINGSVERBAND REGIO EINDHOVEN,Regionale Eenheid Oost-Brabant,,,NaN,,,N,

## Gridcodes

In [20]:
# Define the SQL query to create the new table
create_table_query = '''
    CREATE TABLE IF NOT EXISTS group15_warehouse.gridcodes AS
        SELECT * FROM data_lake.gridcodes;
'''
cursor.execute(create_table_query)
conn_psycopg2.commit()

In [21]:
# Execute SQL query to fetch distinct category types
query = '''
    SELECT * 
    FROM group15_warehouse.gridcodes;
'''

cursor.execute(query)

# Fetch all rows
gridcodes_rows = cursor.fetchall()

# Fetch column names
column_names = [desc[0] for desc in cursor.description]

# Convert the fetched data into a pandas DataFrame
gridcodes = pd.DataFrame(gridcodes_rows, columns=column_names)

display(gridcodes)

,cbs_code,area,x,y,buurtcode,buurtnaam
0,-1,-1,NULL,NULL,Onbekend,Onbekend
1,E1055N4032,10003,4.6732125,51.615944,BU07580909,Buitengebied Prinsenbeek
2,E1055N4033,10003,4.6731982,51.616844,BU07580909,Buitengebied Prinsenbeek
3,E1055N4034,10003,4.6731839,51.617741,BU07580909,Buitengebied Prinsenbeek
4,E1055N4035,10003,4.6731701,51.618641,BU07580909,Buitengebied Prinsenbeek
...,...,...,...,...,...,...
13264,E1055N4027,10003,4.6732831,51.61145,BU07580909,Buitengebied Prinsenbeek
13265,E1055N4028,10003,4.6732693,51.61235,BU07580909,Buitengebied Prinsenbeek
13266,E1055N4029,10003,4.673255,51.613247,BU07580909,Buitengebied Prinsenbeek
13267,E1055N4030,10003,4.6732407,51.614147,BU07580909,Buitengebied Prinsenbeek
13268,E1055N4031,10003,4.6732268,51.615047,BU07580909,Buitengebied Prinsenbeek

## Closing the connection

In [22]:
# Close the cursor and connection
conn_psycopg2.close()
cursor.close()